{
 "title": "阿里云 RDS Exporter Dashboard",
 "tags": [ "aliyun-rds-exporter" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "DBInstanceId",
    "query": "label_values(aliyun_rds_status, DBInstanceId)"
   }
  ]
 },
 "panels": [
  {
   "title": "阿里云RDS实例状态信息",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (LockMode, Engine, ExpireTime, CreateTime, DBInstanceType, RegionId, EngineVersion, DBInstanceStatus, PayType, DBInstanceId, DBInstanceDescription) (aliyun_rds_status)"
    }
   ]
  },
  {
   "title": "CPU和内存利用率(%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_MemCpuUsage_cpuusage{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} CPU使用率"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_MemCpuUsage_memusage{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 内存使用率"
    }
   ]
  },
  {
   "title": "当前连接数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_Sessions_active_session{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 当前活跃连接数"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_Sessions_total_session{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 当前总连接数"
    }
   ]
  },
  {
   "title": "网络流量（单位KB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_NetworkTraffic_recv_k{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 平均每秒输入流量"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_NetworkTraffic_sent_k{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 平均每秒发出流量"
    }
   ]
  },
  {
   "title": "IOPS（单位:次/秒）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_IOPS_io{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} IOPS"
    }
   ]
  },
  {
   "title": "磁盘空间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_resource_usage_DiskUsed{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 已用空间（DataSize+LogSize）"
    },
    {
     "expr": "aliyun_rds_resource_usage_DataSize{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 数据文件占用空间"
    },
    {
     "expr": "aliyun_rds_resource_usage_LogSize{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 日志占用空间"
    },
    {
     "expr": "aliyun_rds_resource_usage_SQLSize{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} SQL的存储量"
    },
    {
     "expr": "aliyun_rds_resource_usage_BackupSize{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 备份占用空间"
    },
    {
     "expr": "aliyun_rds_resource_usage_BackupOssDataSize{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} OSS中备份集的数据文件大小"
    },
    {
     "expr": "aliyun_rds_resource_usage_BackupOssLogSize{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} OSS中备份集的日志文件大小"
    }
   ]
  },
  {
   "title": "TPS(平均每秒事务数）/QPS(平均每秒SQL语句执行次数)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_QPSTPS_QPS{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} QPS(平均每秒SQL语句执行次数)"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_QPSTPS_TPS{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} TPS(平均每秒事务数）"
    }
   ]
  },
  {
   "title": "InnoDB缓存读命中率、使用率、脏块率(%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_InnoDBBufferRatio_ibuf_read_hit{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 缓冲池读命中率%"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_InnoDBBufferRatio_ibuf_use_ratio{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 缓冲池利用率%"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_InnoDBBufferRatio_ibuf_dirty_ratio{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 缓冲池脏块百分比%"
    }
   ]
  },
  {
   "title": "InnoDB读写量（单位为KB）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_InnoDBDataReadWriten_inno_data_read{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} InnoDB平均每秒读取数据量(KB)"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_InnoDBDataReadWriten_inno_data_written{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} InnoDB平均每秒写入数据量(KB)"
    }
   ]
  },
  {
   "title": "InnoDB日志读/写/fsync",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_InnoDBLogWrites_Innodb_log_write_requests{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 平均每秒日志写请求数"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_InnoDBLogWrites_Innodb_log_writes{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 平均每秒向日志文件物理写次数"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_InnoDBLogWrites_Innodb_os_log_fsyncs{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 平均每秒向日志文件完成fsync写次数"
    }
   ]
  },
  {
   "title": "MySQL_COMDML",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_COMDML_com_delete{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 平均每秒delete语句执行次数"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_COMDML_com_insert{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 平均每秒insert语句执行次数"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_COMDML_com_insert_select{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 平均每秒insert_select语句执行次数"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_COMDML_com_replace{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 平均每秒replace语句执行次数"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_COMDML_com_replace_select{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 平均每秒replace_select语句执行次数"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_COMDML_com_select{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 平均每秒select语句执行次数"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_COMDML_com_update{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 平均每秒update语句执行次数"
    }
   ]
  },
  {
   "title": "MySQL_RowDML",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aliyun_rds_performance_MySQL_RowDML_Inno_log_writes{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 平均每秒向日志文件的物理写次数"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_RowDML_inno_row_delete{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 平均每秒从InnoDB表删除的行数"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_RowDML_inno_row_insert{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 平均每秒从InnoDB表插入的行数"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_RowDML_inno_row_readed{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 平均每秒从InnoDB表读取的行数"
    },
    {
     "expr": "aliyun_rds_performance_MySQL_RowDML_inno_row_update{instanceId=~\"$DBInstanceId\"}",
     "legendFormat": "{{ instanceId }} 平均每秒从InnoDB表更新的行数"
    }
   ]
  }
 ]
}